apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-server
  labels:
    app: nginx-server
  namespace: metricas
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: nginx-server
  template:
    metadata:
      labels:
        app: nginx-server
    spec:
      containers:
      - name: nginx-server
        image: nginx:1.19.4
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m