apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-server-demo
  namespace: sandbox
  labels:
    app: nginx-server-demo
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: backend
  template:
    metadata:
      labels:
        tier: backend
    spec:
      containers:
      - name: nginx-server-demo
        image: nginx:1.19.4
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 256Mi
      