apiVersion: v1
kind: Service
metadata: 
  name: nginx-server-service3
spec:
  selector:
    app: nginx-server-replicaset
  type: NodePort
  ports:
  - protocol: TCP
    nodePort: 30010
    port: 80
    targetPort: 80