apiVersion: apps/v1
kind: Deployment
metadata: 
  name: myapp-blue
  labels:
    app: myapp-blue
  namespace: exercise-5
spec: 
  replicas: 3
  selector:
    matchLabels:
      app: myapp
      version: v1.0
  template:
    metadata:
      labels:
        app: myapp
        version: v1.0
    spec:
      containers:
      - name: myapp-blue
        image: gonzadev001/myapp:v1
