apiVersion: apps/v1
kind: Deployment
metadata: 
  name: myapp-green
  labels:
    app: myapp-green
  namespace: exercise-5
spec: 
  replicas: 3
  selector:
    matchLabels:
      app: myapp
      version: v2.0
  template:
    metadata:
      labels:
        app: myapp
        version: v2.0
    spec:
      containers:
      - name: myapp-blue
        image: gonzadev001/myapp:v2
        ports:
        - containerPort: 8080
