apiVersion: v1
kind: Service
metadata:
  name: myapp-svc
  labels:
    app: myapp-svc
  namespace: exercise-5
spec:
  selector:
    app: myapp
    version: v1.0
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
