apiVersion: apps/v1
kind: Deployment
metadata: 
  name: myapp-deployment
  labels:
    app: myapp-deployment
  namespace: sandbox
spec: 
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: gonzadev001/myapp:v2
        ports:
        - name: http
          containerPort: 8080
